:labname: OpenShift Cluster Access with CLI
include::../tools/00_0_Lab_Header_Template.adoc[]
:linkattrs:

:ocp_base: shared.na.openshift.opentlc.com
:ocp_api: https://api.{ocp_base}:6443


// Following the suggestion from https://asciidoctor.org/docs/user-manual/#applying-substitutions
:markup-in-source: verbatim,attributes,quotes
// and then use it as:
//[source,java,subs="{markup-in-source}"]

== {labname} Lab

.Goals
* Find, download, and install the `oc` command from a cluster
* Understand the role of the `$HOME/.kube/config` file
* Find the login URL for a cluster
* Log in to the cluster using the command line
* Access different clusters and switch between them
* Retrieve information about your session: username, server name, and token
* Understand the role of cluster credentials and the `KUBECONFIG` variable
* Learn how to protect your OpenShift user token

.Scenario
You are an application developer and you want to deploy your application to an OpenShift cluster.
The cluster administrator provided you with the cluster's domain name and your username and password credentials.
You want to log in to the cluster and prepare for application deployment.

== Download and Install Command Line Tool

As of Red Hat OpenShift Container Platform version 4.1, you can download the `oc` command line tool directly from the cluster.
This ensures that the command line tool matches your cluster's version and obviates the need to search for an appropriate version.

For Linux^(R)^, the default location is `https://downloads-openshift-console.apps.${CLUSTER_DOMAIN_NAME}/amd64/linux/oc`.
The cluster's domain name for this lab is `{ocp_base}`. Outside the lab environment, this value may be different--ask
your cluster administrator for the cluster domain name.

Then you download the command line tool and move it to the directory that is included in your `$PATH`.
Finally, you make sure that the file is executable.

. Log in to the `client vm` host using your favorite SSH client and your OPENTLC credentials.
. Run the following commands to download `oc`, install it, and make sure it is marked executable:

[source,bash,subs="{markup-in-source}"]
----
$ *wget --no-check-certificate https://downloads-openshift-console.apps.{ocp_base}/amd64/linux/oc*
$ *sudo mv oc /usr/local/bin/oc*
$ *sudo chmod a+x /usr/local/bin/oc*
----

#### Click text to execute

[source,bash,role=execute-1]
----
echo "execute in terminal 1"
----

[source,bash,role=execute-2]
----
echo "execute in terminal 2"
----

[source,bash,role=execute]
----
echo "execute in terminal 1"
----

#### Click text to copy

[source,bash,role=copy]
----
echo "copy text to buffer"
----

#### Click text to copy (and edit)

[source,bash,role=copy-and-edit]
----
echo "copy text to buffer"
----

#### Interrupt command

[source,bash,role=execute]
----
sleep 3600
----

[source,bash,role=execute]
----
<ctrl-c>
----

#### Variable interpolation

base_url: %base_url%

console_url: %console_url%

terminal_url: %terminal_url%

slides_url: %slides_url%

username: %username%

project_namespace: %project_namespace%

cluster_subdomain: %cluster_subdomain%

image_registry: %image_registry%

#### Web site links

link:https://www.openshift.com[External]

link:%base_url%[Internal]

#### Console links

link:%console_url%[Projects]

link:%console_url%/overview/ns/%project_namespace%[Status]

link:%console_url%/k8s/ns/%project_namespace%/events[Events]

link:%console_url%/k8s/ns/%project_namespace%/pods[Pods]

#### Terminal links

link:%terminal_url%[Embedded]

link:%terminal_url%/session/1[Session 1]

link:%terminal_url%/session/2[Session 2]
